swagger: '2.0'
info:
    title: KokteilideretseptuuriNimekiri
    version: 1.0.0
    description: Help to find cocktail recipes
paths:
    /recipes:
        get:
            tags:
                - Recipes
            responses:
                '200':
                    description: Send 200 when recipe is created in databse.
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            - Margarita
                            - Corpse Reviver
                            - Mojito
                            - Queen Mary
                            - Mint Julep
                            - Pina Colada
            summary: Get all the <Recipes> in API
            description: Return all cocktail recipes that are registered in API
        post:
            tags:
                - Recipes
            parameters:
                -
                    name: body
                    description: The <Recipe> that is to be created.
                    schema:
                        $ref: '#/definitions/new-Recipe'
                    in: body
                    required: true
            responses:
                '201':
                    description: Send 201 when <Recipe> is successfully added to the database
                    schema:
                        $ref: '#/definitions/new-Recipe'
                '400':
                    description: 'Missing some parameter, please review your request data.'
                    schema:
                        $ref: '#/definitions/error'
            summary: Create a new <Recipe> into the app
            description: 'Create a new <Recipe> instance with its required details, for further usage.'
    '/recipes/{RecipeID}/':
        get:
            tags:
                - Recipes
            responses:
                '200':
                    description: Returns all details of the given <Recipe>
            summary: Get full details of a <Recipe>
            description: Will return all details of a given <Recipe> based on RecipeID given.
        put:
            tags:
                - Recipes
            parameters:
                -
                    name: body
                    description: Contains new data to be changed in the specified Recipe
                    schema:
                        $ref: '#/definitions/new-Recipe'
                    in: body
                    required: true
            responses:
                '201':
                    description: Returns 201 upon successful modification of recipe
                    schema:
                        $ref: '#/definitions/new-Recipe'
                    examples:
                        application/json:
                            -
                                Name: ''
                                Description: '2'
                                Beverage: ''
                                UserScore: 3.5
                '400':
                    description: Returns bad request when one or multiple parameters are missing
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: 'cannot change info, because some paremeter missing.'
                '404':
                    description: 'Returns 404 when Recipe is to be modified, is not by the given RecipeID'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json: |-
                            [
                                {"error: "Recipe not found."}
                            ]
        delete:
            tags:
                - Recipes
            responses:
                '204':
                    description: Returns "No Content" when removal of <Recipe> is successful
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: No Content
                '404':
                    description: Returns error when <Recipe> with specified ID does not exist
                    examples:
                        application/json:
                            -
                                error: Id not found
            summary: Delete a <Recipe> from the app
            description: Deletes and entry from the app to never be seen again.
        parameters:
            -
                name: RecipeID
                description: ID of Recipe
                in: path
                required: true
                type: string
    /users:
        get:
            tags:
                - Users
            responses:
                '200':
                    description: Returns all details of all Users
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json: |-
                            [   {
                                "UserID":"sfsdfsdf"
                                "UserName":"fxddfh"
                                "IsAdmin":"false"
                                },
                                
                                {
                                "UserID":"sfsdfsdf"
                                "UserName":"fxddfh"
                                "IsAdmin":"false"
                                },
                                
                                {
                                "UserID":"sfsdfsdf"
                                "UserName":"fxddfh"
                                "IsAdmin":"false"
                                }
                            ]
            summary: 'Returns a list of all users, with limited details'
            description: 'Returns a list of all users, with limited details'
        post:
            tags:
                - Users
            parameters:
                -
                    name: body
                    schema:
                        $ref: '#/definitions/new-User'
                    in: body
                    required: true
            responses:
                '201':
                    description: Send 201 when user is successfully added to the database
                    schema:
                        $ref: '#/definitions/new-Recipe'
                    examples:
                        application/json:
                            -
                                FullName: MyName LastName
                                EmailAddress: a@a.com
                                PasswordHASH: abc123
                                PhoneNumber2FA: 12 23423 23423
                                UserName: KoooliKoll
                                IsAdmin: boolean
                '400':
                    description: >-
                        Sends code 400 when request body missing any or multiple of the required parameters
                        for a new User are not present. 
                    schema:
                        $ref: '#/definitions/new-User'
                    examples:
                        application/json: |4

                                [
                                   ({error:`Missing some parameter: ${errors}`})
                                ]
            summary: Adds new Users to the app
            description: 'Enables user signup functions, and furhter usage.'
    /userRatings:
        get:
            tags:
                - UserRatings
            responses:
                '200':
                    description: Send 200 when there is a UserRatings from database to show
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            -
                                UserID: 019b1e0e-7034-70bd-a5dc-4d69c3818e49
                                RecipeID: ee9cb6f9-ca98-4666-8e9b-1153e4ffa32f
                                Score: '4.8'
                                Comment: Best Cocktail Recipe ever
                            -
                                UserID: dd891aad-aae2-45dd-94c2-5daca44be2f5
                                RecipeID: ee9cb6f9-ca98-4666-8e9b-1153e4ffa32f
                                Score: '2.1'
                                Comment: 'Meh, I have seen better!'
            summary: Get the list of all <UserRatings> in API
            description: Return all users UserRatings that are registered in API
        post:
            tags:
                - UserRatings
            parameters:
                -
                    name: body
                    description: User gives comment and rating about given recipe.
                    schema:
                        $ref: '#/definitions/new-UserRating'
                    in: body
                    required: true
            responses:
                '201':
                    description: Send 201 when UserRating is successfully added to the database
                    schema:
                        $ref: '#/definitions/new-UserRating'
                    examples:
                        application/json:
                            -
                                UserID: 019bc766-d172-77fd-803a-1bf46ba9b884
                                RecipeID: 4c523d71-01be-48b2-bada-562b737ed69e
                                UserScore: '4.8'
                                UserComment: Best Cocktail Recipe ever
                '400':
                    description: >-
                        Sends code 400 when request body missing any or multiple of the required parameters
                        for a new UserRating are not present. 
                    schema:
                        $ref: '#/definitions/new-UserRating'
                    examples:
                        application/json:
                            -
                                UserID: 019b1e0e-7034-70bd-a5dc-4d69c3818e49
                                RecipeID: ee9cb6f9-ca98-4666-8e9b-1153e4ffa32f
                                Score: ''
                                Comment: Best Cocktail Recipe ever
            summary: Adds user UserRating into the app
    '/users/{UserID}':
        get:
            tags:
                - Users
            parameters:
                -
                    name: UserID
                    description: ID of existing User
                    in: path
                    required: true
                    type: string
            responses:
                '200':
                    description: Returns all details of a given User
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json: |4
                               {
                                "UserID":"019bc766-d172-77fd-803a-1bf46ba9b884"
                                "FullName":"Test"
                                "UserName":"Test"
                                "EmailAddress":"test@test.com"
                                "IsAdmin":"false"
                                }
                '404':
                    description: Returns repsonse that user is not found
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json: |4

                                [
                                    "error":"User not found"
                                ]
            summary: Get all details of an existing User
            description: 'Will return all details of a given User, based on UserID given'
        put:
            tags:
                - Users
            parameters:
                -
                    name: UserID
                    description: ID of existing User
                    in: path
                    required: true
                    type: string
                -
                    name: body
                    schema:
                        $ref: '#/definitions/new-User'
                    in: body
                    required: true
            responses:
                '200':
                    description: Returns response code 200 when User details where successfuly updated
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            UserID: 019bc766-d172-77fd-803a-1bf46ba9b884
                            FullName: Updated FullName
                            UserName: UpdatedUser
                            EmailAddress: updated@updated.com
                            IsAdmin: false
                '400':
                    description: Returns response code 400 when required parameters are missing
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            error: Some parameters are missing. Please try again!
                '404':
                    description: 'Returns response code 404 when such UserID does not exist '
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            error: User not found
                '409':
                    description: Returns response code 409 when current Username or email are currently taken
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            error: Email address is already in use by another user.
            summary: Updates details of an existing User
            description: 'Will change certain details of a given User, based on given UserID'
        delete:
            tags:
                - Users
            parameters:
                -
                    name: UserID
                    description: ID of existing User
                    in: path
                    required: true
                    type: string
            responses:
                '204':
                    description: Returns response code 204 "No Content" when User deletion was successful
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            -
                                error: No Content
                '404':
                    description: 'Returns response code 404 when such User does not exist '
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            error: User not found
            summary: Deletes a existing User from the app
            description: Deletes a User data from the app permanently.
    '/userRatings/{UserRatingID}':
        get:
            tags:
                - UserRatings
            parameters:
                -
                    name: UserRatingID
                    description: ID of UserRating
                    in: path
                    required: true
                    type: string
            responses:
                '200':
                    description: Returns all details of a certain UserRating
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json: |4

                               {
                                    "UserID": "019bc767-0e18-746f-9741-f66ae5d01483",
                                    "RecipeID": "d5c9b567-6782-44cb-8b33-694ac1927f27",
                                    "UserScore": "4.8",
                                    "UserComment": "Best Cocktail Recipe ever"
                                }
                '400':
                    description: Invalid request syntax.
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            -
                                error: 'cannot give info, because some parameters are missing.'
                '404':
                    description: Returns repsonse that UserRating is not found
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json: |-
                            [
                                [
                                    "error":"UserRating not found"
                                ]
                            ]
            summary: Get all details of an existing UserRating
            description: 'Will return all details of a given UserRating, based on given UserRatingID'
        put:
            tags:
                - UserRatings
            parameters:
                -
                    name: UserRatingID
                    description: ID of UserRating
                    in: path
                    required: true
                    type: string
                -
                    name: body
                    description: Contains new data to be changed in the specified UserRating
                    schema:
                        $ref: '#/definitions/new-UserRating'
                    in: body
                    required: true
            responses:
                '201':
                    description: Returns 201 upon successful modification of UserRating details
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json: |4

                                {
                                    "UserID": "019bc767-0e18-746f-9741-f66ae5d01483",
                                    "RecipeID": "d5c9b567-6782-44cb-8b33-694ac1927f27",
                                    "UserScore": "4.8",
                                    "UserComment": "Best Cocktail Recipe ever"
                                }
                '400':
                    description: Returns bad request when one or multiple parameters are missing
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            -
                                error: 'cannot give info, because some parameters are missing.'
                '404':
                    description: Returns repsonse that UserRating is not found
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json: |-
                            [
                                [
                                    "error":"UserRating not found"
                                ]
                            ]
            summary: Modifies parameters of an existing UserRating
            description: 'Will change certain details of a given UserRating, based on given UserRatingID'
        delete:
            tags:
                - UserRatings
            parameters:
                -
                    name: UserRatingID
                    description: ID of UserRating
                    in: path
                    required: true
                    type: string
            responses:
                '204':
                    description: Returns "No Content" when removal of <UserRating> is successful
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: No Content
                '404':
                    description: Returns error when <UserRating> with specified ID does not exist
                    examples:
                        application/json:
                            -
                                error: Id not found
            summary: Delete a registered user <UserRating> from the app
            description: Deletes and entry from the app to never be seen again.
    /auth/register:
        post:
            tags:
                - Users
            parameters:
                -
                    name: body
                    description: Registering new User
                    schema:
                        $ref: '#/definitions/new-User'
                    in: body
                    required: true
            responses:
                '201':
                    description: Send 201 when new <User> is successfully added into the database
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            FullName: MyName LastName
                            EmailAddress: a@a.com
                            PasswordHASH: abc123
                            PhoneNumber2FA: 12 23423 23423
                            UserName: KoooliKoll
                            IsAdmin: false
                '400':
                    description: 'Missing some parameter, please review your request data.'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            FullName: MyName LastName
                            EmailAddress: ''
                            PasswordHASH: ''
                            PhoneNumber2FA: 12 23423 23423
                            UserName: KoooliKoll
                            IsAdmin: false
                '409':
                    description: Current email/username is in use.
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                FullName: MyName LastName
                                EmailAddress: a@a.com
                                PasswordHASH: abc123
                                PhoneNumber2FA: 12 23423 23423
                                UserName: KoooliKoll
                                IsAdmin: false
                            -
                                FullName: MyName LastName
                                EmailAddress: b@b.com
                                PasswordHASH: abc123
                                PhoneNumber2FA: 12 23423 23423
                                UserName: KoooliKoll
                                IsAdmin: false
            summary: Registers a new <User> into the app
            description: 'Creates a new <User> instance with its required details, for further usage.'
    '/auth/{LoginEmail}':
        get:
            tags:
                - Users
                - Auth
            parameters:
                -
                    name: LoginEmail
                    description: Email by which the user is logging in
                    in: path
                    required: true
                    type: string
            responses:
                '200':
                    description: 'Returns 200, when User with valid email address is found'
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json: |4
                               {
                                "UserID":"019bc766-d172-77fd-803a-1bf46ba9b884"
                                "FullName":"Test"
                                "UserName":"Test"
                                "EmailAddress":"test@test.com"
                                "IsAdmin":"false"
                                }
                '400':
                    description: Return response 400 LoginEmail is missing.
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json: |4

                                {
                                    "Error": "Missing LoginEmail"
                                }
                '404':
                    description: Return response 404 when user with this email is not found.
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json: |4+

                                   {
                                       (Error:"User with this Email does not exist")
                                       
                                   }

            summary: Get a user by their Email address
        parameters:
            -
                name: LoginEmail
                in: path
                required: true
    /sessions:
        post:
            tags:
                - Users
                - Auth
            parameters:
                -
                    name: body
                    description: Data of the user
                    schema:
                        $ref: '#/definitions/login-User'
                    in: body
                    required: true
            responses:
                '200':
                    description: Returns selected user data for the site functioning
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            UserID: 019bb2c4-630f-777b-9413-a826435bf3b8
                            DisplayName: KoooliKoll
                            EmailAddress: a@a.co
                            IsAdmin: false
                '400':
                    description: Returns bad request when parameters are missing.
                    schema:
                        $ref: '#/definitions/error'
                '401':
                    description: 'Returns "Access Denied" when incorrect data is inserted. '
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: Password mismatch
                '404':
                    description: Returns response when user is not found
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: User not found
            summary: Make session get cookie
            description: Inserts a sesion object into database and gives user a cookie
    /sessions/me:
        get:
            tags:
                - Users
                - Auth
            responses:
                '200':
                    description: 'Respond 200, when refresh if login was successful'
                    schema:
                        $ref: '#/definitions/loggedIn-User'
                    examples:
                        application/json:
                            UserID: 019bc766-d172-77fd-803a-1bf46ba9b884
                            FullName: KoooliKoll
                            EmailAddress: a@a.com
                            IsAdmin: false
                '401':
                    description: 'Returns 401, when reauthentification of User was unsuccessful'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: 'Session expired, please log in again.'
            summary: Endpoint to refresh login.
    /auth/logout:
        delete:
            tags:
                - Users
                - Auth
            responses:
                '200':
                    description: Responds 200 OK when removal of session and logout of the user is successful
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json: |4

                                {
                                    "ok":"Session successfully eliminated."
                                }
                '401':
                    description: 'Response 401 when User is trying to log out, without being logged in'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json: |4

                                {
                                    "error": "User is not logged in"
                                }
                '500':
                    description: 'Response 500, when attempting to delete uncaught error occures'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json: |4

                                {
                                    "error": "Server error, please hold."
                                }
            summary: Remove a session when the on User requests
definitions:
    new-Recipe:
        title: Root Type for new-Recipe
        description: ''
        required:
            - Beverage
            - Description
            - Name
        type: object
        properties:
            Name:
                type: string
            Description:
                type: string
            Beverage:
                type: string
            UserScore:
                format: double
                description: ''
                type: number
        example:
            Name: NewRecipeName
            Description: NewRecipeDescription
            Beverage: NewRecipeBeverage
            UserScore: '4.8'
    error:
        description: ''
        type: object
        example:
            error: Error message
    delete-Recipe:
        title: Root Type for delete-Recipe
        description: ''
        type: object
        properties:
            RecipeID:
                type: string
        example:
            RecipeID: d280a328-0835-4be0-b752-222d5c2f938f
    new-User:
        title: Root Type for new-User
        description: 'New User data, PhoneNumber2FA is optional'
        type: array
        items:
            type: string
        example:
            FullName: MyName LastName
            EmailAddress: a@a.com
            PasswordHASH: abc123
            PhoneNumber2FA: 12 23423 23423
            UserName: KoooliKoll
            IsAdmin: false
    new-UserRating:
        title: Root Type for new-userRating
        description: ''
        type: object
        properties:
            Score:
                type: string
            Comment:
                type: string
        example:
            UserID: 019bc767-0e18-746f-9741-f66ae5d01483
            RecipeID: d5c9b567-6782-44cb-8b33-694ac1927f27
            UserScore: '4.8'
            UserComment: Best Cocktail Recipe ever
    login-User:
        title: Root Type for login-User
        description: Data that the User provides upon an attempt to login
        type: object
        properties:
            Email:
                type: string
            Password:
                type: string
        example:
            Email: abc@abc.com
            Password: abc123
    loggedIn-User:
        title: Root Type for leggedIn-User
        description: 'Data of the user, that is returned upon successful new session, or reauthenticating old session'
        type: object
        properties:
            UserID:
                type: string
        example:
            UserID: 019bb2c4-630f-777b-9413-a826435bf3b8
            FullName: KoooliKoll
            EmailAddress: a@a.co
            IsAdmin: false
